version: '3.8'
services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: manager
    ports:
      - "8080:8080"
    networks:
      - crack_net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: worker
    networks:
      - crack_net

networks:
  crack_net:
    driver: bridge
